/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntrenmanRouteImport } from './routes/antrenman'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as KesfetRouteImport } from './routes/kesfet'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OlculerRouteImport } from './routes/olculer'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ApiExMediaRouteImport } from './routes/api/ex-media'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntrenmanRoute = AntrenmanRouteImport.update({
  id: '/antrenman',
  path: '/antrenman',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const KesfetRoute = KesfetRouteImport.update({
  id: '/kesfet',
  path: '/kesfet',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OlculerRoute = OlculerRouteImport.update({
  id: '/olculer',
  path: '/olculer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExMediaRoute = ApiExMediaRouteImport.update({
  id: '/api/ex-media',
  path: '/api/ex-media',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antrenman': typeof AntrenmanRoute
  '/ayarlar': typeof AyarlarRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kesfet': typeof KesfetRoute
  '/login': typeof LoginRoute
  '/olculer': typeof OlculerRoute
  '/profil': typeof ProfilRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/api/ex-media': typeof ApiExMediaRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antrenman': typeof AntrenmanRoute
  '/ayarlar': typeof AyarlarRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kesfet': typeof KesfetRoute
  '/login': typeof LoginRoute
  '/olculer': typeof OlculerRoute
  '/profil': typeof ProfilRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/api/ex-media': typeof ApiExMediaRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antrenman': typeof AntrenmanRoute
  '/ayarlar': typeof AyarlarRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kesfet': typeof KesfetRoute
  '/login': typeof LoginRoute
  '/olculer': typeof OlculerRoute
  '/profil': typeof ProfilRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/api/ex-media': typeof ApiExMediaRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antrenman'
    | '/ayarlar'
    | '/bildirimler'
    | '/kesfet'
    | '/login'
    | '/olculer'
    | '/profil'
    | '/program'
    | '/register'
    | '/api/ex-media'
    | '/u/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antrenman'
    | '/ayarlar'
    | '/bildirimler'
    | '/kesfet'
    | '/login'
    | '/olculer'
    | '/profil'
    | '/program'
    | '/register'
    | '/api/ex-media'
    | '/u/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/antrenman'
    | '/ayarlar'
    | '/bildirimler'
    | '/kesfet'
    | '/login'
    | '/olculer'
    | '/profil'
    | '/program'
    | '/register'
    | '/api/ex-media'
    | '/u/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntrenmanRoute: typeof AntrenmanRoute
  AyarlarRoute: typeof AyarlarRoute
  BildirimlerRoute: typeof BildirimlerRoute
  KesfetRoute: typeof KesfetRoute
  LoginRoute: typeof LoginRoute
  OlculerRoute: typeof OlculerRoute
  ProfilRoute: typeof ProfilRoute
  ProgramRoute: typeof ProgramRoute
  RegisterRoute: typeof RegisterRoute
  ApiExMediaRoute: typeof ApiExMediaRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antrenman': {
      id: '/antrenman'
      path: '/antrenman'
      fullPath: '/antrenman'
      preLoaderRoute: typeof AntrenmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesfet': {
      id: '/kesfet'
      path: '/kesfet'
      fullPath: '/kesfet'
      preLoaderRoute: typeof KesfetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olculer': {
      id: '/olculer'
      path: '/olculer'
      fullPath: '/olculer'
      preLoaderRoute: typeof OlculerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ex-media': {
      id: '/api/ex-media'
      path: '/api/ex-media'
      fullPath: '/api/ex-media'
      preLoaderRoute: typeof ApiExMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntrenmanRoute: AntrenmanRoute,
  AyarlarRoute: AyarlarRoute,
  BildirimlerRoute: BildirimlerRoute,
  KesfetRoute: KesfetRoute,
  LoginRoute: LoginRoute,
  OlculerRoute: OlculerRoute,
  ProfilRoute: ProfilRoute,
  ProgramRoute: ProgramRoute,
  RegisterRoute: RegisterRoute,
  ApiExMediaRoute: ApiExMediaRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
